[package]
name = "ruxnasm"
version = "0.1.0"
authors = ["Karol Belina <karolbelina@gmail.com>"]
edition = "2018"

[[bin]]
name = "ruxnasm"
required-features = ["codespan-reporting"]

[features]
default = ["codespan-reporting"]

[dependencies]
codespan-reporting = { version = "0.11.1", optional = true }
