name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          ARCHIVE_NAME: ruxnasm-x86_64-unknown-linux-gnu.tar.gz
        - os: windows-latest
          ARCHIVE_NAME: ruxnasm-x86_64-pc-windows-msvc.zip
        - os: macos-latest
          ARCHIVE_NAME: ruxnasm-x86_64-apple-darwin.tar.gz

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
    - name: Build Ruxnasm
      run: cargo build --release
    - name: Bundle Ruxnasm
      if: matrix.os == 'windows-latest'
      run: Compress-Archive -CompressionLevel Optimal -Force -Path target/release/ruxnasm.exe -DestinationPath ${{ matrix.ARCHIVE_NAME }}
    - name: Bundle Ruxnasm
      if: matrix.os != 'windows-latest'
      run: tar -C target/release -czf ${{ matrix.ARCHIVE_NAME }} ruxnasm
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.ARCHIVE_NAME }}
        path: ${{ matrix.ARCHIVE_NAME }}

  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
    - name: Test Ruxnasm
      run: cargo test
