name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          ARCHIVE_NAME: ruxnasm-x86_64-unknown-linux-gnu.tar.gz
        - os: windows-latest
          ARCHIVE_NAME: ruxnasm-x86_64-pc-windows-msvc.zip
        - os: macos-latest
          ARCHIVE_NAME: ruxnasm-x86_64-apple-darwin.tar.gz

    steps:
    - name: Get tag
      id: tag
      uses: dawidd6/action-get-tag@v1
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
    - name: Build Ruxnasm
      run: cargo build --release
    - name: Bundle Ruxnasm
      if: matrix.os == 'windows-latest'
      run: Compress-Archive -CompressionLevel Optimal -Force -Path target/release/ruxnasm.exe -DestinationPath ${{ matrix.ARCHIVE_NAME }}
    - name: Bundle Ruxnasm
      if: matrix.os != 'windows-latest'
      run: tar -C target/release -czf ${{ matrix.ARCHIVE_NAME }} ruxnasm
    - name: Upload release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ${{ matrix.ARCHIVE_NAME }}
        asset_name: ${{ matrix.ARCHIVE_NAME }}
        tag: ${{ github.ref }}
        overwrite: true
